#!/bin/sh -e

ell_version=0.26

wget https://mirrors.edge.kernel.org/pub/linux/libs/ell/ell-$ell_version.tar.xz
tar xvf "ell-$ell_version.tar.xz"
cp -r "ell-$ell_version/ell" ../ell

autoreconf -fis
./configure
make
make check
