#!/bin/sh
#
# Simple script to generate iwd network files.

[ "$1" ] || {
    printf '%s\n' "usage: printf pass | ${0##*/} ssid" >&2
    exit 1
}

# Read the password from 'stdin'. This is the simplest
read -r pass

# The SSID appears verbatim in the name if it contains
# only alphanumeric characters, spaces, underscores or
# minus signs. Otherwise it is encoded as an equal sign
# followed by the lower-case hex encoding of the name.
case $1 in
    *[!A-Za-z0-9-_' ']*)
        ssid="=$(printf %s "$1" | od -vA n -t x1 | tr -d '\n ')"
    ;;

    *)
        ssid=$1
    ;;
esac

printf '%s\n\n' "Save this output to /var/lib/iwd/$ssid.psk" >&2
printf '[Security]\n'
printf 'Passphrase=%s\n' "$pass"
printf '\n%s\n' "TIP: You can use this output directly as the" >&2
printf '%s\n'   "     help messages are printed to stderr." >&2
