#!/bin/sh -e

ell_version=0.26

mkdir -p .cache build-aux
cd .cache
wget https://mirrors.edge.kernel.org/pub/linux/libs/ell/ell-$ell_version.tar.xz
tar xvf "ell-$ell_version.tar.xz"
cp -R "ell-$ell_version/ell/" ../ell
cd ..

autoreconf -fis
./configure --disable-manual-pages
make
make check
